pipeline {
    agent{
        docker{
            image 'maven:3.6.1-jdk-8-slim'
            args '-v $HOME/.m2:/root/.m2'
        }
    } 
    stages {
        stage ("build") {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling working app'
                dir ('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage ("test") {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Test on worker app'
                dir ('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage ("package") {
            when {
                branch 'master'
                changeset "**/worker/**"
                steps {
                    echo 'Packaging working app'
                    dir ('worker') {
                        sh 'mvn package -DskipTests'
                        archiveArtifacts artifacts: '**/target/*.jar',
                        fingerprint: true
                    }
                }
            }
        }
        post {
            always {
                echo 'Building multibranch pipeline for worker is completed..'
            }
        }
    }
}
