  pipeline {
    agent any
    tools {
      maven 'maven 3.6.1'
    }
    stages {
      stage("build") {
        when {
          changeset "**/worker/**"
        }
        steps {
          echo 'Compiling worker app..'
          dir('worker') {
            sh 'mvn compile'
          }
        }
      }
      stage("test") {
        when {
          changeset "**/worker/**"
        }
        steps {
          echo 'Running Unit Tets on worker app..'
          dir('worker') {
            sh 'mvn clean test'
          }
        }
      }
      stage("package") {
        when {
          branch 'master'
          changeset "**/worker/**"
        }
        steps {
          echo 'Packaging worker app'
          dir('worker') {
            sh 'mvn package -DskipTests'
            archiveArtifacts artifacts: '**/target/*.jar',
              fingerprint: true
          }
        }
      }
      stage('docker-package'){
        agent any
          steps {
          echo 'Packaging worker app with docker'
            script {
              docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') { 
                def workerImage = docker.build("danylokaras/worker:v${env.BUILD_ID}", "./ worker")
                workerImage.push()
                workerImage.push("latest")
              }
            }
          }
        }
      }
    post {
      always {
        echo 'Building multibranch pipeline for worker is completed..'
      }
    }
  }